require that creates obligation targets aren't added when overriding methods
kelloggm/object-construction-checker pull request #376
Opened 2021-04-07 23:53 UTC by kelloggm

This change will, I hope, fix #368. It doesn't address the problem directly, because I realized that the real issue behind #368 is that `run()` is overridden to add an `@CreatesObligation` annotation, but it could be dynamically-dispatched to by an object of static type `Runnable` but that is dynamically the anonymous class we defined. This problem isn't unique to anonymous classes; you'll see in the test cases that I was able to trigger the unsoundness without needing one.

I'm not convinced that my solution is great: I've restricted the places where `@CreatesObligation` can be written by adding a new kind of error that's issued when a method with fewer `@CreatesObligation` targets is overridden by one with more. Note that because `@CreatesObligation` is inheritable, in practice this means that it's only permitted to write a new obligation annotation on a method that isn't overriding anything. I think that's not too restrictive of a requirement, but I'm curious what you all think.

2021-04-08 16:47 UTC, msridhar requested changes
This is a good fix!  But it doesn't fully fix the original issue I identified, particularly in the case with non-static inner classes.  I added a new test to show the remaining issue.

2021-04-09 00:12 UTC, kelloggm commented
@msridhar I've fixed the underlying bug with `this` expressions now, so I think this is ready for review again. 

I also fixed up the code that handles `@CreateObligation` generally in a few places - before, it wasn't checking that every target was valid, and was instead issuing a `reset.not.owning` error only when ALL targets were invalid. That's fixed. 

I also simplified/fixed the code that handles `@CreateObligation` elsewhere, in particular the parsing and removing duplicate code for getting the expressions.

2021-04-09 00:20 UTC, msridhar commented
Will review later or tomorrow. Could you merge back the `always-call-checker` branch? There have been a couple changes landed there.

2021-04-09 00:28 UTC, kelloggm commented
@msridhar I've merged `always-call-checker` in. No hurries on the review - sorry this became a bit bloated. I can break it into 2 or 3 changes if it's too much.

2021-04-09 21:00 UTC, msridhar approved these changes
Looks great!  Just one tiny nit

2021-04-09 21:00 UTC, msridhar commented on object-construction-checker/tests/mustcall/CreatesObligationInnerClass.java
> +            // this should be disallowed! not sure of the right error message
we can get rid of this comment I think

2021-04-10 00:23 UTC, merged